name: Sync to NPM

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Check if GitHub Token exists
        run: |
          if [ -z "$PERSONAL_ACCESS_TOKEN" ]; then
            echo "GitHub Token is not set. Please set it in your Secrets."
            exit 1
          else
            echo "GitHub Token is set! Proceed with the workflow."
          fi
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
